@startuml
cloud "Cloud Provider" {
  node "Web Server" {
    component "App Server"
  }
  node "Database Server" {
    component "SQL Database"
  }
}

cloud "Client Network" {
  node "Client Device" {
    component "Mobile App"
  }
}

"Client Device" --> "App Server" : Sends Requests
"App Server" --> "SQL Database" : Fetches Data
@enduml
