@startuml 
actor User
entity System

User -> System: Masukkan Username dan Password
System -> System: Verifikasi Username dan Password
alt Valid
    System -> User: Login Sukses (Halaman Dashboard)
else Invalid
    System -> User: Paesan Error (Username atau Password Salah)
end

@enduml